MSGraphOffice365 : Feature : 5 New Actions
splunk-soar-connectors/msgraphforoffice365 pull request #49
Opened 2024-11-28 23:33 UTC by unapped

New actions are:
[get named location ] - Get metadata for the specified named location
[add named location ip ] - Add the specified IP range to the named location
[disable mailbox rules ] - Disable rules for the specified mailbox
[delete mailbox rule ] - Delete the specified mailbox rule
[add user to group ] - Add the specified user to the specified group

## Pull Request Checklist
#### Please check if your PR fulfills the following requirements:
- [x ] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [X] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [X] If this is a new connector or you are adding new actions
    - [X] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [X] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [X] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [X] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [X] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2025-03-13 22:18 UTC, mnordby-splunk commented
Re-targeting this PR from next to main

2025-05-13 13:56 UTC, grokas-splunk commented on office365.json
> +    "app_version": "3.1.2",
I think this should be a minor 3.2.0 release with these actions not a patch release.

2025-05-13 14:05 UTC, grokas-splunk commented on office365_connector.py
> +        display_name = param["display_name"]
Inconsistent param names `display_name` (here) and `displayName` (_handle_add_named_location_ip). Should be consistent

2025-05-13 14:07 UTC, grokas-splunk commented on office365.json
> +                "displayName": {
Inconsistent param naming between actions (camel and snake used) (should be consistent)

2025-05-13 14:08 UTC, grokas-splunk commented on office365_connector.py
> +        endpoint = "/identity/conditionalAccess/namedLocations/{0}".format(location_id)
Not sure where `location_id` is defined here?

2025-05-13 14:09 UTC, grokas-splunk commented on office365_connector.py
> +        endpoint = "/identity/conditionalAccess/namedLocations/{0}".format(location_id)
`/identity/conditionalAccess/namedLocations/{0}` should be moved to consts file

2025-05-13 14:10 UTC, grokas-splunk commented on office365_connector.py
> +    # MARK: i think this one will be broken
If this is broken we should not be including it. Can you please confirm the status of where this is at?

2025-05-13 14:11 UTC, grokas-splunk requested changes
Some issues identified that need to be resolved before moving forward 🙏

2025-09-30 23:36 UTC, closed without merging